version: '0.0'
name: ef-core-assignment1

services:
  ef_core_assignment1.webapi:
    image: ${DOCKER_REGISTRY-}efcoreassignment1webapi
    container_name: api
    build:
      context: .
      dockerfile: EF_Core_Assignment1.WebAPI/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sql-server
    networks:
      - api_network

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    hostname: "sqlserver"
    user: root
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"  # Change this to a strong password
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - api_network

networks:
  api_network:
    driver: bridge  

volumes:
  sql_data:
