version: '3.4'

services:
  ef_core_assignment1.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - SQLSERVER_CONNECTION_STRING=Server=sqlserver;Database=nashtech;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    ports:
      - "8080"
